### PR TITLE
add support for jira api token

### PR DESCRIPTION
**Pull request by nemui**

### CODE REVIEW

**Comment by tomasbjerre** [comment]
@nemui did you notice the failure?

**Comment by nemui** [comment]
fixed!

**Comment by tomasbjerre** [comment]
Releasing this as 2.22. Did not have much time to test it.

**Comment by nemui** [comment]
Nice!  
Providing credentials id for basic auth will probably not work, I'm usually using withCredentials wrapper. If anyone misses this feature - it can easily be added.

**Comment by tomasbjerre** [comment]
This should work:

```groovy
withCredentials([string(credentialsId: 'mycredentialsid', variable: 'tokenVariable')]) {
 def changelogContext = gitChangelog returnType: 'CONTEXT',
  from: [type: 'REF', value: 'git-changelog-1.50'],
  to: [type: 'REF', value: 'master'],
  jira: [issuePattern: 'JENKINS-([0-9]+)\\b', basicAuthString: tokenVariable, server: '...']
}
```

**Comment by nemui** [comment]
For sure - this is exactly how I am using it. 
Looking at the source code, I got the impression that username/password for Jira support Jenkins credentials in a more advance way?

**Comment by tomasbjerre** [comment]
Ah right! I see what you mean. 

Yes, but I don't mind. I assume most people use pipeline anyway and I don't see any point in doing it that way when using pipelines.

**Pull request merged**
